const parallaxStyle = {
  parallax: {
    height: "90vh",
    maxHeight: "1000px",
    overflow: "hidden",
    position: "relative",
    backgroundPosition: "center center",
    backgroundSize: "cover",
    margin: "0",
    padding: "0",
    border: "0",
    display: "flex",
    alignItems: "center",
  },
  separateBottom: {
    position: "absolute",
    width: "100%",
    backgroundColor: "inherit",
    borderColor: "inherit",
    zIndex: 2,
    bottom: "0px",
    // "&::before": {
    //   content: "''",
    //   width: "0",
    //   height: "0",
    //   borderStyle: "solid",
    //   borderColor: "#e5e5e5",
    //   borderWidth: "24.8px 0 0 50vw",
    //   borderLeftWidth: "55vw",
    //   top: "-23px",
    //   borderTopColor: "transparent",
    //   borderBottomColor: "transparent",
    //   right: "0",
    //   position: "absolute",
    //   zIndex: "9",
    //   transform: "rotateY(-180deg)",
    // },
    // "&::after": {
    //   content: "''",
    //   width: 0,
    //   height: 0,
    //   borderStyle: "solid",
    //   borderColor: "#e5e5e5",
    //   borderWidth: "25.2px 0 0 50vw",
    //   borderLeftWidth: "55vw",
    //   position: "absolute",
    //   zIndex: 9,
    //   top: "-24px",
    //   borderTopColor: "transparent",
    // },
  },
  filter: {
    "&:before": {
      background: "rgba(0, 0, 0, 0.5)",
    },
    "&:after,&:before": {
      position: "absolute",
      zIndex: "1",
      width: "100%",
      height: "100%",
      display: "block",
      left: "0",
      top: "0",
      content: "''",
    },
  },
  small: {
    height: "380px",
  },
};

export default parallaxStyle;
